// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubvencionesApp.Infrastructure.Database;

#nullable disable

namespace SubvencionesApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250815132836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Accion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanEstrategicoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Acciones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Agrupacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Agrupaciones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Ayuda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<Guid>("InstrumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganismoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoBeneficiarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Ayudas_ExternalId");

                    b.ToTable("Ayudas");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.AyudaEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<Guid>("InstrumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TipoBeneficiarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_AyudasEstados_ExternalId");

                    b.ToTable("AyudasEstados");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Beneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("IX_Beneficiarios_Identificacion");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Beneficiarios_Nombre");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Concesion", b =>
                {
                    b.Property<long>("IdConcesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdConcesion"));

                    b.Property<Guid?>("BeneficiarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConvocatoriaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Ejercicio")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaConcesion")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ReferenciaBDNS")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenciaPublicacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdConcesion");

                    b.HasIndex("BeneficiarioId")
                        .HasDatabaseName("IX_Concesiones_BeneficiarioId");

                    b.HasIndex("ConvocatoriaId")
                        .HasDatabaseName("IX_Concesiones_ConvocatoriaId");

                    b.HasIndex("Ejercicio")
                        .HasDatabaseName("IX_Concesiones_Ejercicio");

                    b.HasIndex("FechaConcesion")
                        .HasDatabaseName("IX_Concesiones_FechaConcesion");

                    b.ToTable("Concesiones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.ConcesionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganismoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConcesionesDetalle_ExternalId");

                    b.HasIndex("OrganismoId");

                    b.ToTable("ConcesionesDetalle");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.ConfiguracionMicroportal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombrePortal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Vpd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesMicroportal");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Convocatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Ejercicio")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Enlace")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Extracto")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Objeto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("OrganismoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaBDNS")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SituacionEntornoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipoConvocatoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipoSubvencionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Ejercicio")
                        .HasDatabaseName("IX_Convocatorias_Ejercicio");

                    b.HasIndex("FechaPublicacion")
                        .HasDatabaseName("IX_Convocatorias_FechaPublicacion");

                    b.HasIndex("OrganismoId");

                    b.HasIndex("ReferenciaBDNS")
                        .HasDatabaseName("IX_Convocatorias_ReferenciaBDNS");

                    b.HasIndex("SituacionEntornoId");

                    b.HasIndex("TipoConvocatoriaId");

                    b.HasIndex("TipoSubvencionId");

                    b.ToTable("Convocatorias");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.ConvocatoriaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documentos")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstrumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganismoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoBeneficiarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConvocatoriasDetalle_ExternalId");

                    b.ToTable("ConvocatoriasDetalle");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.DatosEstadisticos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TotalConcesiones")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DatosEstadisticos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.EnlaceMicroVentana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_EnlacesMicroVentana_ExternalId");

                    b.ToTable("EnlacesMicroVentana");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Entidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Finalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Finalidades");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.FormaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.GrandeBeneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_GrandesBeneficiarios_ExternalId");

                    b.ToTable("GrandesBeneficiarios");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Instrumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Instrumentos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Linea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Lineas");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Minimis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Minimis_ExternalId");

                    b.ToTable("Minimis");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Objetivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PlanEstrategicoDetalleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanEstrategicoDetalleId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Organismo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Organismos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.OrganosCodigoAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAdmin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("OrganosCodigoAdmin");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.PartidoPolitico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganismoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_PartidosPoliticos_ExternalId");

                    b.ToTable("PartidosPoliticos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.PlanEstrategico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanesEstrategicos_ExternalId");

                    b.ToTable("PlanesEstrategicos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.PlanEstrategicoDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanesEstrategicosDetalle_ExternalId");

                    b.ToTable("PlanesEstrategicosDetalle");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Plazo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConvocatoriaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ConvocatoriaId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Plazos_ExternalId");

                    b.ToTable("Plazos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Provincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Reglamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Reglamentos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Sancion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SancionTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sanciones_ExternalId");

                    b.ToTable("Sanciones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.SancionDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganismoId")
                        .HasColumnType("uuid");

                    b.Property<string>("SancionTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_SancionesDetalle_ExternalId");

                    b.ToTable("SancionesDetalle");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.SectorProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("SectoresProductos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.SituacionEntorno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SituacionesEntorno");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.SubtipoSubvencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubtiposSubvencion");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Suscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Suscripciones_ExternalId");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Tercero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Terceros_ExternalId");

                    b.ToTable("Terceros");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.TipoBeneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TiposBeneficiario");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.TipoConvocatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TiposConvocatoria");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.TipoOrganismo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TiposOrganismo");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.TipoSubvencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TiposSubvencion");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Tramo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tramos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.UnidadAdministrativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v1()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UnidadesAdministrativas");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Concesion", b =>
                {
                    b.HasOne("SubvencionesApp.Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany("Concesiones")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SubvencionesApp.Domain.Entities.Convocatoria", "Convocatoria")
                        .WithMany("Concesiones")
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beneficiario");

                    b.Navigation("Convocatoria");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.ConcesionDetalle", b =>
                {
                    b.HasOne("SubvencionesApp.Domain.Entities.Beneficiario", "Beneficiario")
                        .WithMany("ConcesionesDetalle")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubvencionesApp.Domain.Entities.Organismo", "Organismo")
                        .WithMany("ConcesionesDetalle")
                        .HasForeignKey("OrganismoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Organismo");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Convocatoria", b =>
                {
                    b.HasOne("SubvencionesApp.Domain.Entities.Organismo", "Organismo")
                        .WithMany("Convocatorias")
                        .HasForeignKey("OrganismoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SubvencionesApp.Domain.Entities.SituacionEntorno", "SituacionEntorno")
                        .WithMany("Convocatorias")
                        .HasForeignKey("SituacionEntornoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SubvencionesApp.Domain.Entities.TipoConvocatoria", "TipoConvocatoria")
                        .WithMany("Convocatorias")
                        .HasForeignKey("TipoConvocatoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SubvencionesApp.Domain.Entities.TipoSubvencion", "TipoSubvencion")
                        .WithMany("Convocatorias")
                        .HasForeignKey("TipoSubvencionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organismo");

                    b.Navigation("SituacionEntorno");

                    b.Navigation("TipoConvocatoria");

                    b.Navigation("TipoSubvencion");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Objetivo", b =>
                {
                    b.HasOne("SubvencionesApp.Domain.Entities.PlanEstrategicoDetalle", "PlanEstrategicoDetalle")
                        .WithMany("Objetivos")
                        .HasForeignKey("PlanEstrategicoDetalleId");

                    b.Navigation("PlanEstrategicoDetalle");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Plazo", b =>
                {
                    b.HasOne("SubvencionesApp.Domain.Entities.Convocatoria", "Convocatoria")
                        .WithMany()
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convocatoria");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Beneficiario", b =>
                {
                    b.Navigation("Concesiones");

                    b.Navigation("ConcesionesDetalle");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Convocatoria", b =>
                {
                    b.Navigation("Concesiones");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.Organismo", b =>
                {
                    b.Navigation("ConcesionesDetalle");

                    b.Navigation("Convocatorias");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.PlanEstrategicoDetalle", b =>
                {
                    b.Navigation("Objetivos");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.SituacionEntorno", b =>
                {
                    b.Navigation("Convocatorias");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.TipoConvocatoria", b =>
                {
                    b.Navigation("Convocatorias");
                });

            modelBuilder.Entity("SubvencionesApp.Domain.Entities.TipoSubvencion", b =>
                {
                    b.Navigation("Convocatorias");
                });
#pragma warning restore 612, 618
        }
    }
}
